### ISSUE TITLE
Links to Vast templates are broken

### ISSUE THREAD

**Issue by advanpix** [ai-dock/kohya_ss#1]
When I click on vast template link, it redirects to https://github.com/ai-dock

**Comment by robballantyne** [comment]
Sorry this is not yet fully working. Links will be updated soon

**Comment by robballantyne** [comment]
Links updated.

This is not yet well tested but I'll close this issue.  Any runtime problems should be made in a separate issue

I intend to test this tomorrow before posting the template links in Vast's discord.
