### ISSUE TITLE
tensorboard log directory

### ISSUE THREAD

**Issue by PetrHuu** [ai-dock/kohya_ss#2]
A possibility to change the tensorboard log directory (currently /opt/kohya_ss/logs ), pls. Thank you.

**Comment by robballantyne** [comment]
Sounds reasonable.  I'll add an environment variable for it ASAP

**Comment by PetrHuu** [comment]
Great! Maybe consider a persistent solution even in case a new pod is created. For example, if /workspace is on network storage, maybe put the log dir parameter it in some startup script placed in /workspace persistently. Thank you.

**Comment by robballantyne** [comment]
completed. You can now specify variable `TENSORBOARD_FLAGS="--logdir /path/to/logs"`

**Comment by PetrHuu** [comment]
> completed. You can now specify variable `TENSORBOARD_FLAGS="--logdir /path/to/logs"`

Great! I confirm it works on runpod as well. 🫶🏻
