### ISSUE TITLE
I can't use your docker with online GPU providers - error, localhost refused. Could you please add config for  dockerfile automatic expose/open port 1111 ? (and addition to the other ports like 8888 for juptyer, 7860, forge, 8188 comfyui)

### ISSUE THREAD

**Issue by madeirafranciscoluxio** [ai-dock/kohya_ss#4]
your docker does not have a command to open/expose the respective ports of 1111 (portal listing services), 8888 (jupyter), (7860) forge and 8188 (comfyui)

So it is not possible to run with GPUs online, only locally - error, local host conections refused because ports are not open/exposed by the docker image config

**Comment by robballantyne** [comment]
expose is just a hint. use `-p`
